### ISSUE TITLE
Auth roadmap: pluggable token authentication (epic)

### ISSUE THREAD

**Issue by silverbucket** [sockethub/sockethub#735]
## Token Authentication System

Sockethub needs opt-in token authentication so operators can control who accesses their instance. Tokens must **never be embedded in web application source code** — they are obtained per-user at runtime through an authentication flow and stored in user-controlled storage.

### Auth Flow

**Pre-shared tokens** (Phase 1) — token goes directly in the Socket.IO handshake, no HTTP exchange needed:

```
Client → Socket.IO handshake: auth: { token: "pre-shared-token" }
       → io.use() middleware validates hash → accept/reject
```

**LDAP / remoteStorage tokens** (Phase 2/3) — client exchanges credentials for a sockethub token via HTTP, then uses it for Socket.IO:

```
Web App (no token) → POST /auth/token { grant_type, credentials... }
                   ← { token, expires_in }
                   → stores token in remoteStorage / sessionStorage (per-user)
                   → Socket.IO handshake: auth: { token }
                   → io.use() middleware validates hash in Redis → accept/reject
```

The `POST /auth/token` endpoint is only needed for backends that exchange external credentials for a sockethub token. Pre-shared tokens skip this entirely.

### Identity Backends (pluggable)

| Backend | Auth mechanism | Use case |
|---|---|---|
| **Pre-shared** | Token directly in Socket.IO handshake | Bots, service accounts, simple deployments. Admin generates via CLI, distributes out-of-band. |
| **LDAP** | `POST /auth/token` with `grant_type: "ldap"` | Organizations running Sockethub internally. Validates username/password via LDAP bind. |
| **remoteStorage OAuth** | `POST /auth/token` with `grant_type: "rs_bearer"` | Core unhosted use case. Verifies RS bearer token via Webfinger discovery. No centralized IdP needed. |

### Client-Side Token Storage

Tokens are stored per-user, never in app source:

| User type | Storage | Persistence |
|---|---|---|
| remoteStorage user | RS module `sockethub-tokens/{instance-host}` | Cross-device via RS sync |
| LDAP/org user | `sessionStorage` keyed by instance URL | Tab lifetime (configurable to `localStorage`) |
| Bot/service | Environment variable or runtime config | Process lifetime |

The client library gains a `TokenProvider` interface with built-in implementations (`RemoteStorageTokenProvider`, `SessionStorageTokenProvider`, `StaticTokenProvider`) and emits `token_required` / `token_expiring` events.

### Token Lifecycle

- **Format:** Opaque, 32-byte random, base64url-encoded. NOT JWTs (simpler, immediately revocable, no claim leakage).
- **Server storage:** SHA-256 hash in Redis (LDAP/RS) or token file (pre-shared), with identity metadata
- **Expiry:** 24h default for LDAP/RS-provisioned (configurable), no expiry for pre-shared
- **Refresh:** Client re-authenticates before expiry using same grant type
- **Revocation:** `DELETE /auth/token` (self), `DELETE /auth/admin/tokens/:hash` (admin). Force-disconnects associated sockets.

### Configuration

```json
{
  "auth": {
    "required": false,
    "tokenTtlSeconds": 86400,
    "backends": {
      "preshared": { "enabled": false, "tokenFile": "" },
      "remoteStorage": { "enabled": false },
      "ldap": {
        "enabled": false,
        "url": "ldap://localhost:389",
        "bindDn": "",
        "bindPassword": "",
        "searchBase": "ou=users,dc=example,dc=com",
        "searchFilter": "(uid={{username}})"
      }
    },
    "rateLimiter": { "windowMs": 60000, "maxAttempts": 10, "blockDurationMs": 300000 }
  }
}
```

`auth.required: false` preserves current open-access behavior (backward compatible).

### Security Model

- **Tokens are the sole access boundary** — CORS `origin: "*"` is by design (unhosted backend). No origin restrictions.
- Timing-safe comparison via `crypto.timingSafeEqual` on SHA-256 hashes
- Auth rate limiter separate from message rate limiter (10 attempts/min per IP, 5min block)
- Per-backend lockout (5 failures per username/webfinger/IP → 30min lockout)
- TLS warning at startup if auth enabled without HTTPS
- Tokens never logged — only hashes after initial issuance

### Implementation Phases

This issue is the roadmap/epic. The work itself is tracked in the per-phase issues below; phases without an issue are not yet scheduled.

- [ ] **1. Pre-shared tokens (MVP)** — #1054 — Socket.IO middleware, HTTP actions bearer auth, `FileTokenStore`, CLI `token:create`, config. No token endpoint needed. *(Targeted for 5.0.)*
- [ ] **2. LDAP backend** — #249 — `POST /auth/token` endpoint introduced here, LDAP bind validation, username lockout, `RedisTokenStore` for dynamically-issued tokens
- [ ] **3. remoteStorage OAuth backend** — *(no issue yet)* — Webfinger discovery, RS bearer token verification (reuses Phase 2 HTTP endpoint and Redis store)
- [ ] **4. Client library token management** — *(no issue yet)* — `TokenProvider` interface, built-in implementations, auto-refresh
- [ ] **5. Admin token management** — *(no issue yet)* — list/revoke endpoints, force-disconnect, CLI commands
